const $=id=>document.getElementById(id);
const categories=["All","AI","Business","Creators","Education","Technology","Africa","Design"];
let active="All";
function esc(s){return String(s).replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));}
function chips(){ $("chips").innerHTML=categories.map(c=>`<button class="chip ${c===active?"active":""}" data-cat="${c}">${c}</button>`).join("");document.querySelectorAll("[data-cat]").forEach(b=>b.onclick=()=>{active=b.dataset.cat;chips();discover();});}
async function discover(){const q=$("search").value.trim();$("results").innerHTML='<div class="empty">Searching HavanaAi…</div>';try{const r=await fetch("/api/discover?q="+encodeURIComponent(q)+"&category="+encodeURIComponent(active));const d=await r.json();$("count").textContent=d.total+" results";$("results").innerHTML=d.results.length?d.results.map(x=>`<article class="card"><span class="cat">${esc(x.category).toUpperCase()}</span><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p><div class="tags">${x.tags.map(t=>`<span>#${esc(t)}</span>`).join("")}</div></article>`).join(""):'<div class="empty">No matches yet. Try another topic.</div>';}catch(e){$("results").innerHTML='<div class="empty">HavanaAi is temporarily offline. Try again.</div>';}}
async function ask(){const prompt=$("prompt").value.trim();if(!prompt)return;const a=$("answer");a.classList.remove("hidden");a.textContent="Thinking…";try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt})});const d=await r.json();a.textContent=d.answer||d.error||"No answer returned.";}catch(e){a.textContent="Could not reach HavanaAi right now.";}}
$("searchBtn").onclick=discover;$("search").onkeydown=e=>{if(e.key==="Enter")discover()};$("askBtn").onclick=ask;$("prompt").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();ask();}};
$("newChat").onclick=()=>{$("prompt").value="";$("answer").classList.add("hidden");$("prompt").focus();};
$("theme").onclick=()=>{document.body.classList.toggle("light");$("theme").textContent=document.body.classList.contains("light")?"☀":"☾";};
if("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(()=>{});
chips();discover();