const express=require("express");
const path=require("path");
const app=express();
const PORT=process.env.PORT||10000;
app.use(express.json({limit:"1mb"}));app.use(express.static(__dirname));
const items=[
{id:1,title:"The future of artificial intelligence",category:"AI",description:"Explore practical ways AI is changing work, creativity and everyday life.",tags:["ai","technology","future"]},
{id:2,title:"Build a digital business from your phone",category:"Business",description:"Practical ideas for turning skills and knowledge into digital products and services.",tags:["business","entrepreneurship","digital"]},
{id:3,title:"Creator trends to explore",category:"Creators",description:"Discover formats and workflows creators are using to reach audiences.",tags:["creator","video","social"]},
{id:4,title:"Learn faster with smart research",category:"Education",description:"Simple habits for finding, comparing and organizing useful information.",tags:["education","research","learning"]},
{id:5,title:"Technology shaping Africa",category:"Africa",description:"Explore technology stories, products and opportunities across African markets.",tags:["africa","technology","innovation"]},
{id:6,title:"Mobile-first product design",category:"Design",description:"Principles for building simple, fast and useful mobile experiences.",tags:["design","mobile","ux"]},
{id:7,title:"How modern AI assistants work",category:"AI",description:"A beginner-friendly overview of models, prompts, tools and retrieval.",tags:["ai","models","learning"]},
{id:8,title:"Research workflow for busy teams",category:"Technology",description:"A repeatable workflow for collecting, comparing and summarizing information.",tags:["research","productivity","teams"]}];
const sessions=new Map();
const MODES={quick:"Answer directly. Be concise, accurate and practical. Lead with the answer.",research:"Act like a research analyst. Break the question into sub-problems, compare evidence when available, state uncertainty, then give a concise conclusion and next steps.",learn:"Teach from first principles using simple examples, then give a short practical exercise or checklist.",create:"Act as a creative/product strategist. Produce concrete options, trade-offs and a ready-to-use draft when appropriate."};
const historyFor=id=>{const k=String(id||"default");if(!sessions.has(k))sessions.set(k,[]);return sessions.get(k);};
app.get("/api/health",(req,res)=>res.json({ok:true,app:"HavanaAi",version:"2.0.0",capabilities:["chat","research","learning","creation","discovery"]}));
app.get("/api/discover",(req,res)=>{const q=String(req.query.q||"").trim().toLowerCase(),cat=String(req.query.category||"All");let out=items.filter(x=>cat==="All"||x.category===cat);if(q){const words=q.split(/\s+/).filter(Boolean);out=out.map(x=>{const hay=[x.title,x.description,x.category,...x.tags].join(" ").toLowerCase();return {...x,score:words.reduce((n,w)=>n+(hay.includes(w)?1:0),0)}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score)}res.json({query:q,category:cat,total:out.length,results:out})});
app.post("/api/chat",async(req,res)=>{const prompt=String(req.body?.prompt||"").trim(),mode=MODES[req.body?.mode]?req.body.mode:"quick",sessionId=String(req.body?.sessionId||"default");if(!prompt)return res.status(400).json({error:"Prompt is required."});const url=process.env.AI_API_URL,key=process.env.AI_API_KEY,model=process.env.AI_MODEL||"default";if(!url||!key)return res.json({mode:"local",answer:"HavanaAi is running in local mode. Connect AI_API_URL, AI_API_KEY and optionally AI_MODEL in Render to unlock full AI reasoning.",capabilities:["Quick answers","Research workflows","Learning mode","Creation mode"]});const history=historyFor(sessionId);const system="You are HavanaAi, a high-efficiency AI assistant built for useful outcomes. "+MODES[mode]+" Never invent facts, sources, browsing, tool use or completed actions. If uncertain, say so. Prefer structured answers, minimal repetition and actionable next steps. When asked to perform a task, do the task.";const messages=[{role:"system",content:system},...history.slice(-12),{role:"user",content:prompt}];try{const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json","Authorization":`Bearer ${key}`},body:JSON.stringify({model,messages,temperature:mode==="quick"?0.2:0.4})});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||"Provider error");const answer=d?.choices?.[0]?.message?.content||d?.output_text;if(!answer)throw new Error("Empty provider response");history.push({role:"user",content:prompt},{role:"assistant",content:answer});sessions.set(sessionId,history.slice(-12));res.json({mode:"ai",answer,sessionId})}catch(e){res.status(502).json({error:"AI service unavailable",detail:e.message})}});
app.post("/api/reset",(req,res)=>{sessions.delete(String(req.body?.sessionId||"default"));res.json({ok:true})});
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"index.html")));
app.listen(PORT,()=>console.log("HavanaAi listening on "+PORT));